// build.rs - Generate Rust FFI bindings for the calc C library
//
// Generated by r2rust-ffi-creator SKILL.
// This build script uses bindgen to generate Rust bindings from calc.h.

use std::path::PathBuf;

fn main() {
    let c_dir = PathBuf::from(".c2rust/c");
    let include_dir = c_dir.join("include");

    // Re-run build.rs if the C header changes
    println!("cargo:rerun-if-changed=.c2rust/c/include/calc.h");
    println!("cargo:rerun-if-changed=build.rs");

    // Link the math library (libm) which is required by calc.c for sqrt()
    // Note: On Linux, we need explicit -lm; on macOS it's implicit
    #[cfg(target_os = "linux")]
    println!("cargo:rustc-link-lib=m");

    // Generate bindings using bindgen
    let bindings = bindgen::Builder::default()
        .header(include_dir.join("calc.h").to_str().unwrap())
        .clang_arg(format!("-I{}", include_dir.display()))
        // Only generate bindings for calc_* functions and types
        .allowlist_function("calc_.*")
        .allowlist_type("calc_.*")
        .allowlist_var("CALC_.*")
        // Generate standard trait impls
        .derive_debug(true)
        .derive_default(true)
        .derive_copy(true)
        .derive_eq(true)
        .derive_hash(true)
        // Generate comments from C source
        .generate_comments(true)
        .generate()
        .expect("Unable to generate bindings for calc.h. Ensure libclang is installed.");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Failed to write bindings.rs");
}
