// src/lib.rs - Rust FFI wrapper for the calc C library
//
// Generated by r2rust-ffi-creator SKILL.
//
// This crate provides:
//   1. A safe Rust API (pub fn calc_add_safe, etc.) using Result<T, CalcError>
//   2. C-compatible exports (#[no_mangle] pub extern "C" fn) that exactly
//      match the original C library's exported symbols.
//
// Symbol compatibility guarantee:
//   All functions marked #[no_mangle] must exactly match the C symbols in
//   .c2rust/c/include/calc.h. Run `scripts/verify_symbols.sh` to confirm.

pub mod ffi;
pub mod error;

pub use error::CalcError;

use std::os::raw::{c_char, c_int, c_double};

// ============================================================================
// Safe Rust API (for Rust callers)
// ============================================================================

/// Add two i32 values, returning Err on overflow.
pub fn add(a: i32, b: i32) -> Result<i32, CalcError> {
    a.checked_add(b).ok_or(CalcError::Overflow)
}

/// Subtract b from a, returning Err on overflow.
pub fn sub(a: i32, b: i32) -> Result<i32, CalcError> {
    a.checked_sub(b).ok_or(CalcError::Overflow)
}

/// Multiply two i32 values, returning Err on overflow.
pub fn mul(a: i32, b: i32) -> Result<i32, CalcError> {
    a.checked_mul(b).ok_or(CalcError::Overflow)
}

/// Divide a by b (integer division, truncation toward zero).
/// Returns Err(DivisionByZero) if b == 0.
pub fn div(a: i32, b: i32) -> Result<i32, CalcError> {
    if b == 0 {
        return Err(CalcError::DivisionByZero);
    }
    a.checked_div(b).ok_or(CalcError::Overflow)
}

/// Compute the absolute value of a.
/// Returns Err(Overflow) for i32::MIN (no positive representation).
pub fn abs_val(a: i32) -> Result<i32, CalcError> {
    a.checked_abs().ok_or(CalcError::Overflow)
}

/// Compute the square root of x.
/// Returns Err(InvalidArgument) if x < 0.0.
pub fn sqrt_val(x: f64) -> Result<f64, CalcError> {
    if x < 0.0 {
        return Err(CalcError::InvalidArgument);
    }
    Ok(x.sqrt())
}

/// Return the library version string.
pub fn version() -> &'static str {
    "1.0.0"
}

// ============================================================================
// C ABI exports (#[no_mangle])
//
// These functions MUST match the signatures in .c2rust/c/include/calc.h
// exactly. Any divergence will be caught by scripts/verify_symbols.sh.
// ============================================================================

/// C export: const char *calc_version(void)
///
/// Returns a pointer to a static version string. Caller must NOT free it.
#[no_mangle]
pub extern "C" fn calc_version() -> *const c_char {
    // Safety: this is a valid null-terminated UTF-8 C string literal
    b"1.0.0\0".as_ptr() as *const c_char
}

/// C export: int calc_add(int32_t a, int32_t b, int32_t *result)
#[no_mangle]
pub extern "C" fn calc_add(a: i32, b: i32, result: *mut i32) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match add(a, b) {
        Ok(val) => {
            // Safety: we just checked that result is non-null
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}

/// C export: int calc_sub(int32_t a, int32_t b, int32_t *result)
#[no_mangle]
pub extern "C" fn calc_sub(a: i32, b: i32, result: *mut i32) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match sub(a, b) {
        Ok(val) => {
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}

/// C export: int calc_mul(int32_t a, int32_t b, int32_t *result)
#[no_mangle]
pub extern "C" fn calc_mul(a: i32, b: i32, result: *mut i32) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match mul(a, b) {
        Ok(val) => {
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}

/// C export: int calc_div(int32_t a, int32_t b, int32_t *result)
#[no_mangle]
pub extern "C" fn calc_div(a: i32, b: i32, result: *mut i32) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match div(a, b) {
        Ok(val) => {
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}

/// C export: int calc_abs(int32_t a, int32_t *result)
#[no_mangle]
pub extern "C" fn calc_abs(a: i32, result: *mut i32) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match abs_val(a) {
        Ok(val) => {
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}

/// C export: int calc_sqrt(double x, double *result)
#[no_mangle]
pub extern "C" fn calc_sqrt(x: c_double, result: *mut c_double) -> c_int {
    if result.is_null() {
        return -1; // CALC_ERR_INVALID
    }
    match sqrt_val(x) {
        Ok(val) => {
            unsafe { *result = val; }
            0
        }
        Err(ref e) => error::error_to_code(e),
    }
}
