// src/ffi.rs - Raw C bindings (generated by bindgen via build.rs)
//
// This module contains the raw extern "C" declarations generated from calc.h.
// Do not edit this file manually - it is auto-generated by build.rs.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
